name: CI

on:
  push:
  pull_request:

env:
# on CI, better dump stack trace in case there is an error
  PLUMED_STACK_TRACE: yes
# use two threads for openMP tests
  PLUMED_NUM_THREADS: 2
# these are used to build required packages
  CC: gcc
  CXX: g++

jobs:

  linux:
    uses: ./.github/workflows/linuxWF.yml
    secrets: inherit

  codecheck:
    uses: ./.github/workflows/codecheckWF.yml
    secrets: inherit

  mac:
    uses: ./.github/workflows/macWF.yml
    secrets: inherit
        
  docker:
    uses: ./.github/workflows/dockerWF.yml
    secrets: inherit

  conda:
    uses: ./.github/workflows/condaWF.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-14 ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install conda
      run: |
        curl -LO https://raw.githubusercontent.com/GiovanniBussi/conda-ci/master/conda-ci
        source ./conda-ci install
        source ./conda-ci install-conda-build
    - name: Build PLUMED
      run: |
        source activate base
        export VERSION=none
        if [[ $GITHUB_REF == "refs/tags/"* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION//-/_}
          VERSION=${VERSION#v}
        fi
        make -C conda
    - name: Deploy
      env:
        CONDA_UPLOAD_TOKEN: ${{ secrets.CONDA_UPLOAD_TOKEN }}
      if: ${{ startsWith( github.ref , 'refs/tags/' ) }}
      run: |
        source activate base
        export CONDA_LABEL=tag
        make -C conda upload
